### ISSUE TITLE
ValueError: invalid login credentials, absent cookie ccsrftoken

### ISSUE THREAD

**Issue by zephyr2k7** [vladimirs-git/fortigate-api#10]
Hi,
after having upgraded the fortigate to version 7.2.4 I get this error
ValueError: invalid login credentials, absent cookie ccsrftoken

I double checked the credentials and the login still work on an old version of fortigate
Ho can I debug this further?

thanks in advance

DC

**Comment by vladimirs-git** [comment]
https://github.com/vladimirs-git/fortigate-api/discussions/8

**Comment by zephyr2k7** [comment]
It's working perfectly thx
