### ISSUE TITLE
Incorrect token validation link

### ISSUE THREAD

**Issue by Christiandus** [vladimirs-git/fortigate-api#31]
In the [token check](https://github.com/vladimirs-git/fortigate-api/blob/401b2c7bde08aff49f57c97603a8ddf765421471/fortigate_api/fortigate_base.py#L147C1-L147C65) the URL that is checked is .../cmdb/system/status. However this is an undocumented endpoint and might not be supported in future FortiOS versions. I propose that that the following endpoint be used instead: .../monitor/system/status

**Comment by aman207** [comment]
This already seems to be the case in 7.4.4

**Comment by vladimirs-git** [comment]
fixed in [2.0.2](https://github.com/vladimirs-git/fortigate-api/releases/tag/2.0.2)
