### ISSUE TITLE
How to manipulate dhcp reserved-address with REST API

### ISSUE THREAD

**Issue by perlang** [vladimirs-git/fortigate-api#5]
hi,

I want to add/delete the system dhcp list with REST API. 
But I could find the proper API.

And my environment is,
python 3.10.6
FortiGate 60E with v6.2.4

Thanks in advanced !

Perlang

**Comment by vladimirs-git** [comment]
version 0.2.6 has implemented [dhcp_server](https://github.com/vladimirs-git/fortigate-api#dhcpserver)
Hope the [examples](https://github.com/vladimirs-git/fortigate-api/blob/main/examples/dhcp_server.py) are helpful

**Comment by perlang** [comment]
hi, Vladimir,
The new version(0.2.6) work smoothly.Thank you very much for your help !
Best Regards,Perlang
----- 原始邮件 -----
发件人：Vladimir Prusakov ***@***.***>
收件人：vladimirs-git/fortigate-api ***@***.***>
抄送人：perlang ***@***.***>,  Author ***@***.***>
主题：Re: [vladimirs-git/fortigate-api] How to manipulate dhcp reserved-address with REST API (Issue #5)
日期：2022年09月07日 14点53分


Closed #5 as completed.
