### ISSUE TITLE
New future

### ISSUE THREAD

**Issue by dima-bzz** [vladimirs-git/fortigate-api#6]
Hello. Is it possible to add execution of execute commands and wake-on-lan command?

**Comment by vladimirs-git** [comment]
Please provide an example of what you expect

**Comment by dima-bzz** [comment]
@vladimirs-git I need to execute this command "execute wake-on-lan OST ad:45:54:da:23:24 2 9 192.168.10.35"

**Comment by vladimirs-git** [comment]
SSH implemented in [fortigate-api 1.0.0](https://pypi.org/project/fortigate-api/1.0.0/)
hope the [SSH examples](https://github.com/vladimirs-git/fortigate-api/blob/main/examples/ssh.py) are helpful
